image: ruby:2.7

pages:
  script:
  - gem install jekyll
  - gem install bundler:2.2.15
  - gem install nokogiri
  - gem install i18n
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
